// Generated by ReScript, PLEASE EDIT WITH CARE


var state = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ""
];

var crossTurn = "x";

var circleTurn = "o";

export {
  state ,
  crossTurn ,
  circleTurn ,
}
/* No side effect */
