// Generated by ReScript, PLEASE EDIT WITH CARE


var state = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ""
];

var winningCombination = [
  [
    0,
    1,
    2
  ],
  [
    3,
    4,
    5
  ],
  [
    6,
    7,
    8
  ],
  [
    0,
    3,
    6
  ],
  [
    1,
    4,
    7
  ],
  [
    2,
    5,
    8
  ],
  [
    0,
    4,
    8
  ],
  [
    2,
    4,
    6
  ]
];

var crossTurn = "x";

var circleTurn = "o";

export {
  state ,
  crossTurn ,
  circleTurn ,
  winningCombination ,
}
/* No side effect */
