// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var x = JsxRuntime.jsx("img", {
      src: "icon-x.svg"
    });

var o = JsxRuntime.jsx("img", {
      src: "icon-o.svg"
    });

function Cell(props) {
  var value = props.value;
  var hoverClass = function (x) {
    switch (x) {
      case "o" :
          return "o-hover";
      case "x" :
          return "x-hover";
      default:
        throw {
              RE_EXN_ID: "Match_failure",
              _1: [
                "Cell.res",
                6,
                28
              ],
              Error: new Error()
            };
    }
  };
  return JsxRuntime.jsx("div", {
              children: value === "x" ? x : (
                  value === "o" ? o : JsxRuntime.jsx(JsxRuntime.Fragment, {})
                ),
              className: "flex justify-center items-center text-6xl mt-2 h-40 w-40 bg-slate-700 rounded-xl cursor-pointer " + hoverClass(props.turn) + "",
              id: "cell",
              onClick: props.onClick
            });
}

var make = Cell;

export {
  x ,
  o ,
  make ,
}
/* x Not a pure module */
