// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var x = JsxRuntime.jsx("img", {
      src: "icon-x.svg"
    });

var o = JsxRuntime.jsx("img", {
      src: "icon-o.svg"
    });

function Cell(props) {
  var value = props.value;
  var hoverClass = function (value, turn) {
    if (value !== "") {
      return "";
    }
    switch (turn) {
      case "o" :
          return "o-hover";
      case "x" :
          return "x-hover";
      default:
        return "";
    }
  };
  return JsxRuntime.jsx("div", {
              children: value === "x" ? x : (
                  value === "o" ? o : JsxRuntime.jsx(JsxRuntime.Fragment, {})
                ),
              className: "flex justify-center items-center text-6xl mt-2 h-40 w-40 bg-slate-700 rounded-xl cursor-pointer " + hoverClass(value, props.turn) + "",
              id: "cell",
              onClick: props.onClick
            });
}

var make = Cell;

export {
  x ,
  o ,
  make ,
}
/* x Not a pure module */
