// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var x = JsxRuntime.jsx("img", {
      height: "50%",
      src: "icon-x.svg",
      width: "50%"
    });

var o = JsxRuntime.jsx("img", {
      height: "50%",
      src: "icon-o.svg",
      width: "50%"
    });

function Cell(props) {
  var value = props.value;
  var hoverClass = function (value, turn) {
    if (value !== "") {
      return "";
    }
    switch (turn) {
      case "o" :
          return "o-hover";
      case "x" :
          return "x-hover";
      default:
        return "";
    }
  };
  return JsxRuntime.jsx("div", {
              children: value === "x" ? x : (
                  value === "o" ? o : JsxRuntime.jsx(JsxRuntime.Fragment, {})
                ),
              className: "flex justify-center items-center text-6xl mt-2 h-20 w-20 md:h-30 md:w-30 lg:h-40 lg:w-40 bg-slate-700 rounded-xl cursor-pointer " + hoverClass(value, props.turn) + " shadow-xl border-2 border-cyan-300",
              id: "cell",
              onClick: props.onClick
            });
}

var make = Cell;

export {
  x ,
  o ,
  make ,
}
/* x Not a pure module */
