// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cell from "../Cell/Cell.bs.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Board(props) {
  var cellClick = props.cellClick;
  var turn = props.turn;
  return JsxRuntime.jsx("div", {
              children: Belt_Array.mapWithIndex(props.cell, (function (index, item) {
                      return JsxRuntime.jsx(Cell.make, {
                                  value: item,
                                  turn: turn,
                                  onClick: (function (param) {
                                      Curry._1(cellClick, index);
                                    })
                                }, String(index));
                    })),
              className: "grid grid-cols-3 mt-10 gap-5",
              id: "board"
            });
}

var make = Board;

export {
  make ,
}
/* Cell Not a pure module */
