// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  var iconTurn = function (whichTrun) {
    switch (whichTrun) {
      case "o" :
          return JsxRuntime.jsx("img", {
                      height: "20",
                      src: "/icon-o.svg",
                      width: "20"
                    });
      case "x" :
          return JsxRuntime.jsx("img", {
                      height: "20",
                      src: "/icon-x.svg",
                      width: "20"
                    });
      default:
        return JsxRuntime.jsx(JsxRuntime.Fragment, {});
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              height: "30",
                              src: "/icon-x.svg",
                              width: "30"
                            }),
                        JsxRuntime.jsx("img", {
                              height: "30",
                              src: "/icon-o.svg",
                              width: "30"
                            })
                      ],
                      className: "flex gap-1"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: iconTurn(props.turn)
                            }),
                        JsxRuntime.jsx("p", {
                              children: props.game ? "Turn" : "Win",
                              className: "text-xl font-bold text-slate-300"
                            })
                      ],
                      className: "flex gap-1 items-center"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              height: "30",
                              src: "/icon-x.svg",
                              width: "30"
                            }),
                        JsxRuntime.jsx("img", {
                              height: "30",
                              src: "/icon-o.svg",
                              width: "30"
                            })
                      ],
                      className: "flex gap-1"
                    })
              ],
              className: "flex gap-10 items-center",
              id: "header"
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
