// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Reset(props) {
  return JsxRuntime.jsx("div", {
              children: "Reset",
              className: "flex justify-center items-center text-lime-300 bg-slate-700 w-40 h-20 rounded-full cursor-pointer text-2xl mt-10 mb-10",
              id: "btn"
            });
}

var make = Reset;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
