// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Board from "./components/Board/Board.bs.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Reset from "./components/Reset/Reset.bs.mjs";
import * as State from "./components/State/State.bs.mjs";
import * as React from "react";
import * as Header from "./components/Header/Header.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return State.state;
      });
  var setCell = match[1];
  var cell = match[0];
  var match$1 = React.useState(function () {
        return State.crossTurn;
      });
  var setTurn = match$1[1];
  var turn = match$1[0];
  var match$2 = React.useState(function () {
        return true;
      });
  var handleClick = function (index) {
    if (cell[index] !== "") {
      return ;
    }
    var newCell = cell.slice(0);
    newCell[index] = turn;
    Curry._1(setCell, (function (param) {
            return newCell;
          }));
    if (turn === State.crossTurn) {
      return Curry._1(setTurn, (function (param) {
                    return State.circleTurn;
                  }));
    } else {
      return Curry._1(setTurn, (function (param) {
                    return State.crossTurn;
                  }));
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {
                      turn: turn
                    }),
                JsxRuntime.jsx(Board.make, {
                      cell: cell,
                      turn: turn,
                      cellClick: handleClick,
                      onGame: match$2[0]
                    }),
                JsxRuntime.jsx(Reset.make, {
                      setBoard: setCell,
                      playerTurn: setTurn
                    })
              ],
              className: "flex flex-col items-center justify-center h-screen lg:my-10"
            });
}

var make = App;

export {
  make ,
}
/* Board Not a pure module */
